create table PLANOCONTA(
	ID INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	TIPO CHAR(1) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE TRANSACAO(ID INT NOT NULL IDENTITY(1,1),
DATA DATETIME NOT NULL,
VALOR DECIMAL(9,2) NOT NULL,
HISTORICO VARCHAR(100),
TIPO CHAR(1) NOT NULL,
PLANOCONTAID INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (PLANOCONTAID) REFERENCES PLANOCONTA(ID)
);